#!/usr/bin/env bash
set -euo pipefail

# Fail loudly: report the line of any unhandled command failure to stderr so a
# pipefail exit is never silent (stdout is reserved for the rendered report).
rc_on_err() { echo "rc-error: ${3##*/}:${2}: command failed (exit ${1}) under 'set -o pipefail'" >&2; }
set -o errtrace
trap 'rc_on_err "$?" "$LINENO" "${BASH_SOURCE[0]}"' ERR

if [[ "${BASH_VERSINFO[0]}" -lt 4 ]]; then
	echo "# Review Council Report"
	echo ""
	echo "**Error:** Bash 4+ is required. macOS ships Bash 3; install a modern version: \`brew install bash\`"
	exit 0
fi

if ! command -v jq >/dev/null 2>&1; then
	echo "# Review Council Report"
	echo ""
	echo "**Error:** jq is required but not installed."
	echo "Install it: \`apt-get install jq\` | \`brew install jq\` | \`dnf install jq\`"
	exit 0
fi

# rc-render-report.sh: renders structured markdown report template
# Usage: rc-render-report.sh <session_dir>
# Outputs: structured markdown report to stdout

session_dir="${1:-}"

# Graceful handling of missing session
if [[ -z "$session_dir" ]] || [[ ! -d "$session_dir" ]]; then
	echo "# Review Council Report"
	echo ""
	echo "Session data not available."
	exit 0
fi

tracking_file="$session_dir/tracking.md"
if [[ ! -f "$tracking_file" ]]; then
	echo "# Review Council Report"
	echo ""
	echo "Session tracking data not found."
	exit 0
fi

evidence_file="$session_dir/verdicts/evidence-check.json"

# Parse tracking.md
mode=$(grep "^- Mode:" "$tracking_file" | cut -d: -f2- | xargs || echo "Unknown")
branch=$(grep "^- Branch:" "$tracking_file" | cut -d: -f2- | xargs || echo "unknown")
base=$(grep "^- Base:" "$tracking_file" | cut -d: -f2- | xargs || echo "main")
pr_line=$(grep "^- PR:" "$tracking_file" | cut -d: -f2- | xargs || echo "none")
agents_discovered=$(grep "^- Agents discovered:" "$tracking_file" | cut -d: -f2- | xargs || echo "0")
agents_absent=$(grep "^- Agents absent:" "$tracking_file" | cut -d: -f2- | xargs || echo "none")
changeset=$(grep "^- Changeset size:" "$tracking_file" | cut -d: -f2- | xargs || echo "unknown")

# Parse evidence-check.json if exists
total_findings=0
verified_count=0
correctable_count=0
stripped_count=0
dedup_count=0
if [[ -f "$evidence_file" ]]; then
	total_findings=$(jq -r '.total_findings // 0' "$evidence_file" 2>/dev/null || echo 0)
	verified_count=$(jq -r '.verified | length' "$evidence_file" 2>/dev/null || echo 0)
	correctable_count=$(jq -r '.correctable | length' "$evidence_file" 2>/dev/null || echo 0)
	stripped_count=$(jq -r '.stripped | length' "$evidence_file" 2>/dev/null || echo 0)
	dedup_count=$(jq -r '.duplicates_consolidated // 0' "$evidence_file" 2>/dev/null || echo 0)
fi

# LLM provenance — models used, to the extent the host recorded them.
# Orchestrator writes one "role: model-id" per line to models.txt before
# rendering (see phases/report.md). Absent file means the host did not
# expose model identity — state that rather than inventing names.
models_file="$session_dir/models.txt"
if [[ -f "$models_file" && -s "$models_file" ]]; then
	# Dedup, preserving order: deep mode dispatches the same agent per
	# subsystem, so models.txt may carry repeated lines.
	models_block=$(awk 'NF && !seen[$0]++' "$models_file" | sed 's/^/- /')
else
	models_block="_Not recorded by the host — reviewer, validator, and coordinator model IDs were not exposed to the report renderer._"
fi

# Start rendering report
cat <<EOF
# Review Council Report

> **This report was generated by an LLM, not a human reviewer.** It was
> produced by the Review Council automated agent panel. Findings are
> machine-generated, may contain errors, and are advisory input to human
> judgment, not a substitute for it.

**Models used** (to the best of the host's disclosure):

$models_block

## Session Information
- **Mode**: $mode
- **Branch**: $branch
- **Base**: $base
- **PR**: $pr_line
- **Session Directory**: $session_dir

## Discovery Summary
- **Agents discovered**: $agents_discovered
- **Agents absent**: $agents_absent
- **Changeset**: $changeset

EOF

# CI Status section if available
ci_status_file="$session_dir/ci-status.txt"
if [[ -f "$ci_status_file" ]]; then
	cat "$ci_status_file"
	echo ""
fi

# Verification Summary
cat <<EOF
## Verification Summary
- **Total findings**: $total_findings
- **Verified**: $verified_count
- **Correctable**: $correctable_count
- **Stripped**: $stripped_count
- **Duplicates consolidated**: $dedup_count

EOF

# Findings by Severity (from verified list)
if [[ -f "$evidence_file" ]] && [[ $verified_count -gt 0 ]]; then
	echo "## Findings by Severity"
	echo ""

	# Extract verified findings and group by severity
	for severity in CRITICAL HIGH MEDIUM LOW; do
		count=$(jq -r --arg sev "$severity" '[.verified[] | select(.severity == $sev)] | length' "$evidence_file" 2>/dev/null || echo 0)
		if [[ $count -gt 0 ]]; then
			echo "### $severity ($count)"
			echo ""
			jq -r --arg sev "$severity" '.verified[] | select(.severity == $sev) | "- **\(.title)** (\(.file), \(.agent))"' "$evidence_file" 2>/dev/null || true
			echo ""
		fi
	done
fi

# Per-agent verdict table
echo "## Per-Agent Verdicts"
echo ""
echo "| Agent | Verdict | Findings |"
echo "|-------|---------|----------|"

# Read verdict files if they exist
verdict_dir="$session_dir/verdicts"
if [[ -d "$verdict_dir" ]]; then
	for verdict_file in "$verdict_dir"/*.md; do
		[[ -f "$verdict_file" ]] || continue
		agent_name=$(basename "$verdict_file" .md)

		# Parse verdict from file (look for REQUEST CHANGES or APPROVE)
		verdict="APPROVE"
		# Match structured verdict: **Verdict**: REQUEST CHANGES or a standalone verdict line
		if grep -qE '^\*\*Verdict\*\*:.*REQUEST CHANGES|^(REQUEST CHANGES)$' "$verdict_file" 2>/dev/null; then
			verdict="REQUEST CHANGES"
		fi

		# Count findings in this agent's verdict
		finding_count=0
		if [[ -f "$evidence_file" ]]; then
			finding_count=$(jq -r --arg agent "$agent_name" '[.verified[] | select(.agent == $agent)] | length' "$evidence_file" 2>/dev/null || echo 0)
		fi

		echo "| $agent_name | $verdict | $finding_count |"
	done
fi

echo ""

# Narrative and learnings markers
cat <<'EOF'
## Council Synthesis

<!-- NARRATIVE -->

The LLM will add narrative synthesis here based on the findings and verdicts above.

## Prior Learnings

<!-- LEARNINGS -->

The LLM will record false positives, validated patterns, and evidence quality feedback here.

EOF

# Source / issue-tracker footer. Override REVIEW_COUNCIL_REPO to point a
# fork's reports at its own repository.
repo_url="${REVIEW_COUNCIL_REPO:-https://github.com/lolables/lola-mod-review-council}"
cat <<EOF
---

_Produced by [Review Council]($repo_url). Found a problem with this review, or want the source? [Open an issue]($repo_url/issues) or browse the [repository]($repo_url)._
EOF

exit 0
