#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPT="$SCRIPT_DIR/../skills/review-council/scripts/rc-render-report.sh"
PASS=0
FAIL=0

# Test 1: Missing session directory
echo "Test 1: Missing session directory"
result=$(bash "$SCRIPT" "/nonexistent/path" 2>/dev/null)
if echo "$result" | grep -qi "not available\|not found\|no session"; then
	echo "  PASS: graceful message for missing session"
	PASS=$((PASS + 1))
else
	echo "  FAIL: no graceful message"
	FAIL=$((FAIL + 1))
fi

# Test 2: Valid session with tracking and evidence data
echo "Test 2: Valid session"
session=$(mktemp -d)
mkdir -p "$session/verdicts"

cat >"$session/tracking.md" <<'TRACKING'
# Review Council Session Tracking

## Phase: Preparation

- Input type: auto
- Forge: local
- Tooling: none
- PR: none
- Linked issues: 0
- Prior reviews: 0
- Constitution: none
- Mode: code (code files changed)
- Branch: feature/auth
- Base: main
- Language: go
- Framework: none
- Agents discovered: 6
- Agents absent: none
- Changeset size: 5 files
TRACKING

cat >"$session/verdicts/evidence-check.json" <<'EVIDENCE'
{
  "verified": [
    {"agent": "divisor-adversary-code", "severity": "HIGH", "title": "Missing input validation", "file": "auth.go", "line": "42", "evidence": "user_input := r.URL.Query()"}
  ],
  "correctable": [],
  "stripped": [
    {"agent": "divisor-testing-code", "severity": "CRITICAL", "title": "Fabricated finding", "file": "fake.go", "line": "", "evidence": "nonexistent", "reason": "FILE_NOT_FOUND"}
  ],
  "total_findings": 3,
  "duplicates_consolidated": 1
}
EVIDENCE

result=$(bash "$SCRIPT" "$session" 2>/dev/null)
if echo "$result" | grep -q "Review Council"; then
	echo "  PASS: report contains header"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing header"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "feature/auth"; then
	echo "  PASS: report contains branch name"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing branch name"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "Missing input validation"; then
	echo "  PASS: report contains verified finding title"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing verified finding title"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "divisor-adversary-code"; then
	echo "  PASS: report contains agent name"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing agent name"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "HIGH"; then
	echo "  PASS: report contains severity level"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing severity level"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "Correctable"; then
	echo "  PASS: report contains correctable count"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing correctable count"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "Changeset"; then
	echo "  PASS: report contains changeset size"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing changeset size"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "generated by an LLM, not a human reviewer"; then
	echo "  PASS: report contains LLM provenance banner"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing LLM provenance banner"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "Not recorded by the host"; then
	echo "  PASS: models fallback shown when models.txt absent"
	PASS=$((PASS + 1))
else
	echo "  FAIL: models fallback missing when models.txt absent"
	FAIL=$((FAIL + 1))
fi
rm -rf "$session"

# Test 3: models.txt is surfaced in the provenance header when present
echo "Test 3: Recorded models surfaced in report"
session=$(mktemp -d)
mkdir -p "$session/verdicts"
cat >"$session/tracking.md" <<'TRACKING'
# Review Council Session Tracking

## Phase: Preparation

- Mode: code (code files changed)
- Branch: feature/auth
- Base: main
- Agents discovered: 6
- Agents absent: none
- Changeset size: 5 files
TRACKING
cat >"$session/models.txt" <<'MODELS'
coordinator: claude-opus-4-8
divisor-adversary-code: claude-sonnet-5
MODELS

result=$(bash "$SCRIPT" "$session" 2>/dev/null)
if echo "$result" | grep -q "claude-opus-4-8" && echo "$result" | grep -q "divisor-adversary-code: claude-sonnet-5"; then
	echo "  PASS: recorded models appear in report"
	PASS=$((PASS + 1))
else
	echo "  FAIL: recorded models missing from report"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "generated by an LLM, not a human reviewer"; then
	echo "  PASS: provenance banner present with recorded models"
	PASS=$((PASS + 1))
else
	echo "  FAIL: provenance banner missing with recorded models"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "github.com/lolables/lola-mod-review-council"; then
	echo "  PASS: default repo footer link present"
	PASS=$((PASS + 1))
else
	echo "  FAIL: default repo footer link missing"
	FAIL=$((FAIL + 1))
fi
rm -rf "$session"

# Test 4: duplicate model lines are deduped in the report
echo "Test 4: Duplicate model lines deduped"
session=$(mktemp -d)
mkdir -p "$session/verdicts"
cat >"$session/tracking.md" <<'TRACKING'
# Review Council Session Tracking

## Phase: Preparation

- Mode: code (code files changed)
- Branch: feature/auth
- Base: main
- Agents discovered: 6
- Agents absent: none
- Changeset size: 5 files
TRACKING
cat >"$session/models.txt" <<'MODELS'
divisor-adversary-code: claude-sonnet-5
divisor-adversary-code: claude-sonnet-5
divisor-guard-code: claude-sonnet-5
MODELS

result=$(bash "$SCRIPT" "$session" 2>/dev/null)
dup_count=$(echo "$result" | grep -c "^- divisor-adversary-code: claude-sonnet-5$")
if [[ "$dup_count" -eq 1 ]]; then
	echo "  PASS: duplicate model line collapsed to one"
	PASS=$((PASS + 1))
else
	echo "  FAIL: expected 1 deduped line, got $dup_count"
	FAIL=$((FAIL + 1))
fi

# Test 5: REVIEW_COUNCIL_REPO overrides the footer link
echo "Test 5: Footer repo link is templated"
result=$(REVIEW_COUNCIL_REPO="https://example.com/fork" bash "$SCRIPT" "$session" 2>/dev/null)
if echo "$result" | grep -q "example.com/fork" && ! echo "$result" | grep -q "github.com/lolables"; then
	echo "  PASS: REVIEW_COUNCIL_REPO override respected"
	PASS=$((PASS + 1))
else
	echo "  FAIL: footer link not overridden by REVIEW_COUNCIL_REPO"
	FAIL=$((FAIL + 1))
fi
rm -rf "$session"

echo ""
echo "Results: $PASS passed, $FAIL failed"
[[ $FAIL -eq 0 ]] && exit 0 || exit 1
