#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPT="$SCRIPT_DIR/../skills/review-council/scripts/rc-render-report.sh"
PASS=0
FAIL=0

# Test 1: Missing session directory
echo "Test 1: Missing session directory"
result=$(bash "$SCRIPT" "/nonexistent/path" 2>/dev/null)
if echo "$result" | grep -qiE "not available|not found|no session"; then
	echo "  PASS: graceful message for missing session"
	PASS=$((PASS + 1))
else
	echo "  FAIL: no graceful message"
	FAIL=$((FAIL + 1))
fi

# Test 2: Valid session with tracking and evidence data
echo "Test 2: Valid session"
session=$(mktemp -d)
mkdir -p "$session/verdicts"

cat >"$session/tracking.md" <<'TRACKING'
# Review Council Session Tracking

## Phase: Preparation

- Input type: auto
- Forge: local
- Tooling: none
- PR: none
- Linked issues: 0
- Prior reviews: 0
- Constitution: none
- Mode: code (code files changed)
- Branch: feature/auth
- Base: main
- Language: go
- Framework: none
- Agents discovered: 6
- Agents absent: none
- Changeset size: 5 files
TRACKING

cat >"$session/verdicts/findings.json" <<'EVIDENCE'
{
  "verified": [
    {"agent": "divisor-adversary-code", "severity": "HIGH", "title": "Missing input validation", "file": "auth.go", "line": "42", "evidence": "user_input := r.URL.Query()", "description": "Query params are used unvalidated.", "recommendation": "Validate before use."}
  ],
  "correctable": [],
  "stripped": [
    {"agent": "divisor-testing-code", "severity": "CRITICAL", "title": "Fabricated finding", "file": "fake.go", "line": "", "evidence": "nonexistent", "reason": "FILE_NOT_FOUND"}
  ],
  "total_findings": 3,
  "duplicates_consolidated": 1,
  "verdicts": {"divisor-adversary-code": "REQUEST CHANGES"}
}
EVIDENCE

result=$(bash "$SCRIPT" "$session" 2>/dev/null)
if echo "$result" | grep -q "Review Council"; then
	echo "  PASS: report contains header"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing header"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "feature/auth"; then
	echo "  PASS: report contains branch name"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing branch name"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "Missing input validation"; then
	echo "  PASS: report contains verified finding title"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing verified finding title"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "divisor-adversary-code"; then
	echo "  PASS: report contains agent name"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing agent name"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "HIGH"; then
	echo "  PASS: report contains severity level"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing severity level"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "Correctable"; then
	echo "  PASS: report contains correctable count"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing correctable count"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "Changeset"; then
	echo "  PASS: report contains changeset size"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing changeset size"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "generated by an LLM, not a human reviewer"; then
	echo "  PASS: report contains LLM provenance banner"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report missing LLM provenance banner"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "Not recorded by the host"; then
	echo "  PASS: models fallback shown when models.json absent"
	PASS=$((PASS + 1))
else
	echo "  FAIL: models fallback missing when models.json absent"
	FAIL=$((FAIL + 1))
fi
# RC_BUGS #2 guard: per-agent table verdict comes from findings.json .verdicts
# (verbatim) and count from verified findings — table cannot disagree with
# the findings listed above it.
if echo "$result" | grep -qF "| divisor-adversary-code | REQUEST CHANGES | 1 |"; then
	echo "  PASS: per-agent table row reflects verdicts map + finding count"
	PASS=$((PASS + 1))
else
	echo "  FAIL: per-agent table row missing or wrong"
	FAIL=$((FAIL + 1))
fi
rm -rf "$session"

# Test 3: models.json is surfaced in the provenance header when present
echo "Test 3: Recorded models surfaced in report"
session=$(mktemp -d)
mkdir -p "$session/verdicts"
cat >"$session/tracking.md" <<'TRACKING'
# Review Council Session Tracking

## Phase: Preparation

- Mode: code (code files changed)
- Branch: feature/auth
- Base: main
- Agents discovered: 6
- Agents absent: none
- Changeset size: 5 files
TRACKING
cat >"$session/models.json" <<'MODELS'
[
  {"role": "coordinator", "id": "claude-opus-4-8"},
  {"role": "divisor-adversary-code", "id": "claude-sonnet-5"}
]
MODELS

result=$(bash "$SCRIPT" "$session" 2>/dev/null)
if echo "$result" | grep -q "claude-opus-4-8" && echo "$result" | grep -q "divisor-adversary-code: claude-sonnet-5"; then
	echo "  PASS: recorded models appear in report"
	PASS=$((PASS + 1))
else
	echo "  FAIL: recorded models missing from report"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "generated by an LLM, not a human reviewer"; then
	echo "  PASS: provenance banner present with recorded models"
	PASS=$((PASS + 1))
else
	echo "  FAIL: provenance banner missing with recorded models"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "github.com/lolables/lola-mod-review-council"; then
	echo "  PASS: default repo footer link present"
	PASS=$((PASS + 1))
else
	echo "  FAIL: default repo footer link missing"
	FAIL=$((FAIL + 1))
fi
rm -rf "$session"

# Test 4: duplicate role/id pairs are deduped in the report
echo "Test 4: Duplicate model entries deduped"
session=$(mktemp -d)
mkdir -p "$session/verdicts"
cat >"$session/tracking.md" <<'TRACKING'
# Review Council Session Tracking

## Phase: Preparation

- Mode: code (code files changed)
- Branch: feature/auth
- Base: main
- Agents discovered: 6
- Agents absent: none
- Changeset size: 5 files
TRACKING
cat >"$session/models.json" <<'MODELS'
[
  {"role": "divisor-adversary-code", "id": "claude-sonnet-5"},
  {"role": "divisor-adversary-code", "id": "claude-sonnet-5"},
  {"role": "divisor-guard-code", "id": "claude-sonnet-5"}
]
MODELS

result=$(bash "$SCRIPT" "$session" 2>/dev/null)
dup_count=$(echo "$result" | grep -c "^- divisor-adversary-code: claude-sonnet-5$")
if [[ "$dup_count" -eq 1 ]]; then
	echo "  PASS: duplicate model line collapsed to one"
	PASS=$((PASS + 1))
else
	echo "  FAIL: expected 1 deduped line, got $dup_count"
	FAIL=$((FAIL + 1))
fi

# Test 5: REVIEW_COUNCIL_REPO overrides the footer link
echo "Test 5: Footer repo link is templated"
result=$(REVIEW_COUNCIL_REPO="https://example.com/fork" bash "$SCRIPT" "$session" 2>/dev/null)
if echo "$result" | grep -q "example.com/fork" && ! echo "$result" | grep -q "github.com/lolables"; then
	echo "  PASS: REVIEW_COUNCIL_REPO override respected"
	PASS=$((PASS + 1))
else
	echo "  FAIL: footer link not overridden by REVIEW_COUNCIL_REPO"
	FAIL=$((FAIL + 1))
fi
rm -rf "$session"

# Test 6: malformed models.json must degrade gracefully, not abort the report.
# Every other jq call in this script has a `2>/dev/null || fallback`; the
# models.json read is a 3-stage pipe (jq | awk | sed) where, under pipefail, a
# jq parse failure propagates as the pipeline's exit code even though awk and
# sed both exit 0 - without a fallback that aborts the whole render with zero
# output. The docs now ask the LLM to hand-maintain this file, so malformed
# input is a realistic failure mode, not a hypothetical.
echo "Test 6: malformed models.json degrades instead of aborting the report"
session=$(mktemp -d)
mkdir -p "$session/verdicts"
cat >"$session/tracking.md" <<'TRACKING'
# Review Council Session Tracking

## Phase: Preparation

- Mode: code (code files changed)
- Branch: feature/auth
- Base: main
- Agents discovered: 6
- Agents absent: none
- Changeset size: 5 files
TRACKING
cat >"$session/verdicts/findings.json" <<'FJ'
{
  "verified": [
    {"agent": "divisor-adversary-code", "severity": "HIGH", "title": "Missing input validation", "file": "auth.go", "line": "42", "evidence": "user_input := r.URL.Query()", "description": "Query params are used unvalidated.", "recommendation": "Validate before use."}
  ],
  "correctable": [], "stripped": [],
  "total_findings": 1, "duplicates_consolidated": 0,
  "verdicts": {"divisor-adversary-code": "REQUEST CHANGES"}
}
FJ
printf '{ not json' >"$session/models.json"

set +e
result=$(bash "$SCRIPT" "$session" 2>/dev/null)
exit_code=$?
set -e
if [[ "$exit_code" -eq 0 ]]; then
	echo "  PASS: script exits 0 despite malformed models.json"
	PASS=$((PASS + 1))
else
	echo "  FAIL: script aborted (exit $exit_code) on malformed models.json"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -qF "| divisor-adversary-code | REQUEST CHANGES | 1 |"; then
	echo "  PASS: report still renders findings and verdict table"
	PASS=$((PASS + 1))
else
	echo "  FAIL: report body missing despite malformed models.json"
	FAIL=$((FAIL + 1))
fi
if echo "$result" | grep -q "Not recorded by the host"; then
	echo "  PASS: models section degrades to not-recorded fallback"
	PASS=$((PASS + 1))
else
	echo "  FAIL: models section did not degrade gracefully"
	FAIL=$((FAIL + 1))
fi
rm -rf "$session"

echo ""

# Test 7: consolidated_from provenance renders folded reviewer angles beneath
# the surviving primary finding, so cross-agent consolidation doesn't erase a
# secondary reviewer's perspective from the report.
echo "Test 7: Consolidated finding angles rendered beneath primary finding"
session=$(mktemp -d)
mkdir -p "$session/verdicts"
cat >"$session/tracking.md" <<'TRACKING'
# Review Council Session Tracking

## Phase: Preparation

- Mode: code (code files changed)
- Branch: feature/auth
- Base: main
- Agents discovered: 6
- Agents absent: none
- Changeset size: 5 files
TRACKING

cat >"$session/verdicts/findings.json" <<'EVIDENCE'
{
  "verified": [
    {"agent": "divisor-adversary-code", "severity": "HIGH", "title": "Missing input validation", "file": "auth.go", "line": "42", "evidence": "user_input := r.URL.Query()", "description": "Query params are used unvalidated.", "recommendation": "Validate before use.",
      "provenance": {"consolidated_from": [{"agent": "divisor-testing-code", "severity": "HIGH", "angle": "untested failure path", "recommendation": "add a test"}]}}
  ],
  "correctable": [],
  "stripped": [],
  "total_findings": 2,
  "duplicates_consolidated": 1,
  "verdicts": {"divisor-adversary-code": "REQUEST CHANGES"}
}
EVIDENCE

result=$(bash "$SCRIPT" "$session" 2>/dev/null)
if echo "$result" | grep -q "untested failure path"; then
	echo "  PASS: folded angle from consolidated_from rendered"
	PASS=$((PASS + 1))
else
	echo "  FAIL: folded angle from consolidated_from missing"
	FAIL=$((FAIL + 1))
fi
rm -rf "$session"

# RC-004 residual: a null/absent per-agent verdict must render UNKNOWN, never
# default to APPROVE (unsafe direction for a security-review tool).
echo "Test: null per-agent verdict renders UNKNOWN, not APPROVE"
session=$(mktemp -d)
mkdir -p "$session/verdicts"
cat >"$session/tracking.md" <<'TRACKING'
# Review Council Session Tracking

## Phase: Preparation

- Mode: code (code files changed)
- Agents discovered: 1
TRACKING
cat >"$session/verdicts/findings.json" <<'EVIDENCE'
{
  "verified": [],
  "correctable": [],
  "stripped": [],
  "total_findings": 0,
  "duplicates_consolidated": 0,
  "verdicts": {"divisor-guard-code": null}
}
EVIDENCE
result=$(bash "$SCRIPT" "$session" 2>/dev/null)
row=$(echo "$result" | grep 'divisor-guard-code' || true)
if echo "$row" | grep -q 'UNKNOWN'; then
	echo "  PASS: null verdict renders UNKNOWN"
	PASS=$((PASS + 1))
else
	echo "  FAIL: null verdict row was '$row'"
	FAIL=$((FAIL + 1))
fi
rm -rf "$session"

echo "Results: $PASS passed, $FAIL failed"
[[ $FAIL -eq 0 ]] && exit 0 || exit 1
