name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install Task
        uses: go-task/setup-task@70f2430ad412f838533de8c0515c749ffb2b8bd3 # v1

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install bash jq

      - name: Run tests
        run: task test
